### 회원가입 1

POST http://localhost:8080/signup
Content-Type: application/json

{
  "username": "spring1",
  "email": "yhwjd99@gmail.com",
  "password": "1234",
  "age": 25
}

### 회원가입

POST http://localhost:8080/signup
Content-Type: application/json

{
  "username": "spring2",
  "email": "yhwjd99@naver.com",
  "password": "4321",
  "age": 23
}